version: "3.3"

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME

volumes:
  pg_data:
