apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: echo-server
spec:
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
  selector:
    app: server

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: echo-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db
